### ISSUE TITLE
Error while setting up smartweatherudp platform for sensor

### ISSUE THREAD

**Issue by VoetenK** [briis/smartweather#58]
Logger: homeassistant.components.sensor
Source: custom_components/smartweatherudp/sensor.py:71
Integration: Sensor (documentation, issues)
First occurred: 3:13:05 PM (1 occurrences)
Last logged: 3:13:05 PM

Error while setting up smartweatherudp platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartweatherudp/sensor.py", line 71, in setup_platform
    module = SWReceiver(config.get(CONF_HOST), DEFAULT_PORT, unit_system)
  File "/usr/local/lib/python3.8/site-packages/pysmartweatherudp/receiver.py", line 35, in __init__
    self._socket.bind((host, port))
socket.gaierror: [Errno -2] Name does not resolve

**Comment by briis** [comment]
Hi,
This is the wrong Integration to report this bug on. There is another Github for the UDP version. Please note, that I do not maintain that Integration anymore, as I don't have HW on my physical location.

https://github.com/briis/smartweatherudp
