### ISSUE TITLE
can't compare datetime.datetime to datetime.date

### ISSUE THREAD

**Issue by verstrepeng** [briis/smartweather#68]
After upgrading via HACS to the latest version, my integration is broken.
In the logs following error:

```
Logger: custom_components.smartweather
Source: helpers/update_coordinator.py:143
Integration: WeatherFlow Smart Weather (documentation, issues)
First occurred: 15:27:54 (2 occurrences)
Last logged: 15:38:32

Unexpected error fetching smartweather data: can't compare datetime.datetime to datetime.date
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.8/site-packages/pysmartweatherio/client.py", line 109, in get_hourly_forecast
    return await self._forecast_data(FORECAST_TYPE_HOURLY, 72)
  File "/usr/local/lib/python3.8/site-packages/pysmartweatherio/client.py", line 402, in _forecast_data
    if today > forecast_time:
TypeError: can't compare datetime.datetime to datetime.date
```

**Comment by briis** [comment]
I made a quick fix that should solve the problem:

Could you edit the file `manifest.json` in `custom_components/smartweather` and change this:

```json
    "requirements": [
        "pysmartweatherio==2.1.8"
    ]
```

to this:

```json
    "requirements": [
        "pysmartweatherio==2.1.9"
    ]
```

Restart Home Assistant, and see if it works?

**Comment by verstrepeng** [comment]
You rock ! It is working again :-)

**Comment by alexdelprete** [comment]
Had the exact same issue, I just upgraded, and can confirm the fix works.

Thanks Bjarne.

**Comment by briis** [comment]
Perfect. I will release the fix to HACS now.
