### ISSUE TITLE
Entry points must be listed in groups

### ISSUE THREAD

**Issue by cinofx** [briis/smartweather#74]
Getting the following while attempting to install the integration portion after adding through hacs:

"config flow could not be loaded"

from log:

```
Logger: homeassistant.util.package
Source: util/package.py:96
First occurred: 7:22:53 PM (1 occurrences)
Last logged: 7:22:53 PM

Unable to install package pysmartweatherio==2.1.10: Keyring is skipped due to an exception: Entry points must be listed in groups ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p2k2v544/pysmartweatherio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p2k2v544/pysmartweatherio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-irpkmc1f cwd: /tmp/pip-install-p2k2v544/pysmartweatherio/ Complete output (24 lines): Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2851, in get_entry_map ep_map = self._ep_map File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2813, in __getattr__ raise AttributeError(attr) AttributeError: _ep_map During handling of the above exception, another exception occurred: Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-p2k2v544/pysmartweatherio/setup.py", line 2, in <module> setup( File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup _setup_distribution = dist = klass(attrs) File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__ for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 641, in <genexpr> for entry in dist.get_entry_map(group).values() File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2853, in get_entry_map ep_map = self._ep_map = EntryPoint.parse_map( File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2538, in parse_map raise ValueError("Entry points must be listed in groups") ValueError: Entry points must be listed in groups ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 21.1.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```Logger: homeassistant.util.package
Source: util/package.py:96
First occurred: 7:22:53 PM (1 occurrences)
Last logged: 7:22:53 PM

Unable to install package pysmartweatherio==2.1.10: Keyring is skipped due to an exception: Entry points must be listed in groups ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p2k2v544/pysmartweatherio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p2k2v544/pysmartweatherio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-irpkmc1f cwd: /tmp/pip-install-p2k2v544/pysmartweatherio/ Complete output (24 lines): Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2851, in get_entry_map ep_map = self._ep_map File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2813, in __getattr__ raise AttributeError(attr) AttributeError: _ep_map During handling of the above exception, another exception occurred: Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-p2k2v544/pysmartweatherio/setup.py", line 2, in <module> setup( File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup _setup_distribution = dist = klass(attrs) File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__ for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 641, in <genexpr> for entry in dist.get_entry_map(group).values() File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2853, in get_entry_map ep_map = self._ep_map = EntryPoint.parse_map( File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2538, in parse_map raise ValueError("Entry points must be listed in groups") ValueError: Entry points must be listed in groups ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 21.1.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by briis** [comment]
What is the environment you are running HA in?

**Comment by cinofx** [comment]
Hi Bjarne,

Thanks for checking in.

Environment is:
Raspberry Pi 3 Model B running Home Assistant OS.

```
➜  ~ ha core info
arch: aarch64
audio_input: None
audio_output: None
boot: true
image: ghcr.io/home-assistant/raspberrypi3-64-homeassistant
ip_address: 172.30.32.1
last_version: 2021.6.6
machine: raspberrypi3-64
port: 8123
ssl: false
update_available: false
version: 2021.6.6
version_latest: 2021.6.6
wait_boot: 600
watchdog: true
```

**Comment by briis** [comment]
I have never had this error reported before, so I searched a bit on the error, and it seems it is related to the Python environment. Just to see if it is your PI setup, could you try and open a terminal on your PI, and enter this command:

`pip3 install pysmartweatherio==2.1.10`

If this works without errors, it is something in the Home Assistant Container. I run on an Intel NUC, with HASS IO.

**Comment by cinofx** [comment]
I had actually done that earlier, so now pip says satisfied:


```
➜  ~ pip3 install pysmartweatherio==2.1.10
Requirement already satisfied: pysmartweatherio==2.1.10 in /usr/lib/python3.8/site-packages (2.1.10)
Requirement already satisfied: asyncio in /usr/lib/python3.8/site-packages (from pysmartweatherio==2.1.10) (3.4.3)
Requirement already satisfied: aiohttp in /usr/lib/python3.8/site-packages (from pysmartweatherio==2.1.10) (3.7.4.post0)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/lib/python3.8/site-packages (from aiohttp->pysmartweatherio==2.1.10) (3.10.0.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/lib/python3.8/site-packages (from aiohttp->pysmartweatherio==2.1.10) (1.6.3)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/lib/python3.8/site-packages (from aiohttp->pysmartweatherio==2.1.10) (5.1.0)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/lib/python3.8/site-packages (from aiohttp->pysmartweatherio==2.1.10) (4.0.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/lib/python3.8/site-packages (from aiohttp->pysmartweatherio==2.1.10) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3.8/site-packages (from aiohttp->pysmartweatherio==2.1.10) (21.2.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3.8/site-packages (from yarl<2.0,>=1.0->aiohttp->pysmartweatherio==2.1.10) (3.1)
```

Funny thing is I am installing this integration as part of a recovery from an SD card crash. So starting over with a fresh HA image and setting things up again. The only difference from my previous environment might be the 64-bit haos image versus the 32-bit I may have been previously running.

**Comment by briis** [comment]
There is something mixed up in your HA installation, since it will install on your PI, but not in your HA environment.
I only have one more suggestion: go to the `custom_components/smartweather` directory and delete the directory `__pycache__`. Then restart and try again.

**Comment by cinofx** [comment]
Unfortunately I do not see that directory. I have, however, tried deleting the smartweather directory entirely, removing via HACS, installing previous versions, etc. I will keep fiddling!

**Comment by cinofx** [comment]
I ordered a new rpi 4 model B and flashed the SD card with the 64-bit image and the installation of the smartweather integration went normally.

Not sure what the issue with the rpi3 is. Didn't work after multiple images, attempts, etc.
